spring:
  application:
    name: ae5-warranty-system
  data:
    mongodb:
      uri: mongodb://localhost:27017/ae5_warranty_db
  web:
    resources:
      add-mappings: false

server:
  port: 8080

logging:
  level:
    root: INFO
    com.example.ae5: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Odoo Configuration
odoo:
  url: http://localhost:8069
  db: odoo
  username: admin@example.com
  password: admin
  api-path: /xmlrpc/2
